const EXERCISES = [
  // ==================== DAY 1 — PUSH ====================

  // Warmup + core
  { day:'Day 1', section:'Warmup + core', name:'Barbell Bench Press', equipment:'Barbell', weight_range:'20 → 50 lbs', sets_target:3, reps_target:'8', instructions:['Lie flat with eyes under bar','Grip slightly wider than shoulder-width','Lower bar to mid-chest slowly','Keep feet flat, back neutral','Press back up fully'], image_key:'barbell-bench-press', superset_group:null, sort_order:1, muscles:{primary:['Chest'],secondary:['Anterior Deltoid','Triceps']} },
  { day:'Day 1', section:'Warmup + core', name:'Barbell Overhead Press', equipment:'Barbell', weight_range:'20 → 40 lbs', sets_target:3, reps_target:'8', instructions:['Stand tall, hold bar at collarbone','Press straight overhead','Keep core tight, avoid leaning','Lower slowly'], image_key:'barbell-overhead-press', superset_group:null, sort_order:2, muscles:{primary:['Anterior Deltoid','Medial Deltoid'],secondary:['Upper Chest','Triceps','Upper Traps']} },

  // Superset A
  { day:'Day 1', section:'Superset A', name:'Dumbbell Front Raise', equipment:'Dumbbells', weight_range:'5 → 10 lbs', sets_target:3, reps_target:'12', instructions:['Stand upright with dumbbells in front of thighs','Palms face the body, arms straight','Raise both arms forward to shoulder height','Avoid momentum or swinging','Lower with control'], image_key:'dumbbell-front-raise', superset_group:'superset-a-d1', sort_order:3, muscles:{primary:['Anterior Deltoid'],secondary:['Upper Chest','Medial Deltoid']} },
  { day:'Day 1', section:'Superset A', name:'Dumbbell Lateral Raise', equipment:'Dumbbells', weight_range:'5 → 10 lbs', sets_target:3, reps_target:'12', instructions:['Stand tall with feet shoulder-width apart','Hold dumbbells at sides with slight elbow bend','Raise arms laterally to shoulder height','Keep palms down, avoid shrugging','Lower slowly with control'], image_key:'dumbbell-lateral-raise', superset_group:'superset-a-d1', sort_order:4, muscles:{primary:['Medial Deltoid'],secondary:['Anterior Deltoid','Upper Traps']} },
  { day:'Day 1', section:'Superset A', name:'Lateral Raise Pulse', equipment:'Dumbbells', weight_range:'3 → 8 lbs', sets_target:3, reps_target:'15', instructions:['Raise dumbbells to shoulder height','Pulse in small top-half reps','Maintain form and shoulder tension'], image_key:'lateral-raise-pulse', superset_group:'superset-a-d1', sort_order:5, muscles:{primary:['Medial Deltoid'],secondary:['Anterior Deltoid']} },

  // Superset B
  { day:'Day 1', section:'Superset B', name:'Overhead Dumbbell Press', equipment:'Dumbbells', weight_range:'8 → 15 lbs', sets_target:3, reps_target:'12', instructions:['Stand with dumbbells at shoulder height','Palms facing forward','Press both arms overhead fully','Engage core and avoid arching back','Lower under control'], image_key:'overhead-dumbbell-press', superset_group:'superset-b-d1', sort_order:6, muscles:{primary:['Anterior Deltoid','Medial Deltoid'],secondary:['Triceps','Upper Chest']} },
  { day:'Day 1', section:'Superset B', name:'Arnold Press', equipment:'Dumbbells', weight_range:'8 → 12 lbs', sets_target:3, reps_target:'10', instructions:['Start with dumbbells in front of shoulders, palms in','Rotate palms out as you press overhead','Keep torso stable, elbows controlled','Reverse on the way down'], image_key:'arnold-press', superset_group:'superset-b-d1', sort_order:7, muscles:{primary:['Anterior Deltoid','Medial Deltoid','Posterior Deltoid'],secondary:['Triceps','Upper Chest']} },
  { day:'Day 1', section:'Superset B', name:'Dumbbell Overhead Hold', equipment:'Dumbbells', weight_range:'5 → 10 lbs', sets_target:3, reps_target:'30s', instructions:['Press dumbbells overhead','Hold with arms straight and core engaged','Avoid arching back'], image_key:'dumbbell-overhead-hold', superset_group:'superset-b-d1', sort_order:8, muscles:{primary:['Anterior Deltoid','Triceps'],secondary:['Core','Upper Traps']} },

  // Superset C
  { day:'Day 1', section:'Superset C', name:'Dumbbell Alternating Bench Press', equipment:'Dumbbells', weight_range:'10 → 20 lbs', sets_target:3, reps_target:'10', instructions:['Lie on bench with dumbbells up','Lower one dumbbell while keeping the other up','Alternate arms, maintain stability'], image_key:'dumbbell-alternating-bench-press', superset_group:'superset-c-d1', sort_order:9, muscles:{primary:['Chest'],secondary:['Anterior Deltoid','Triceps','Core']} },
  { day:'Day 1', section:'Superset C', name:'Tricep Kickback', equipment:'Dumbbells', weight_range:'5 → 10 lbs', sets_target:3, reps_target:'12 per arm', instructions:['Support one hand and knee on bench','Hold dumbbell in opposite hand, elbow bent','Extend arm straight behind you','Squeeze triceps, then return slowly','Keep torso still'], image_key:'tricep-kickback', superset_group:'superset-c-d1', sort_order:10, muscles:{primary:['Triceps'],secondary:['Posterior Deltoid']} },
  { day:'Day 1', section:'Superset C', name:'Incline Dumbbell Chest Press', equipment:'Incline Bench, Dumbbells', weight_range:'10 → 20 lbs', sets_target:3, reps_target:'10', instructions:['Set bench to 30–45° incline','Sit back with dumbbells at chest','Press up and slightly inward','Elbows at ~45° angle from torso','Lower slowly with control'], image_key:'incline-dumbbell-chest-press', superset_group:'superset-c-d1', sort_order:11, muscles:{primary:['Upper Chest'],secondary:['Anterior Deltoid','Triceps']} },

  // Cables
  { day:'Day 1', section:'Cables', name:'Cable Tricep Pushdown', equipment:'Rope Attachment', weight_range:'10 → 25 lbs', sets_target:3, reps_target:'12', instructions:['Attach rope at high pulley','Elbows fixed at sides, pull rope down','Fully extend arms, squeeze triceps','Return slowly without swinging'], image_key:'cable-tricep-pushdown', superset_group:null, sort_order:12, muscles:{primary:['Triceps'],secondary:['Forearms']} },
  { day:'Day 1', section:'Cables', name:'Single Arm Cable Chest Press', equipment:'Cable Machine', weight_range:'10 → 25 lbs', sets_target:3, reps_target:'10 per arm', instructions:['Set pulley at chest height','Stand in split stance','Press handle forward to full arm extension','Keep core engaged and stable'], image_key:'single-arm-cable-chest-press', superset_group:null, sort_order:13, muscles:{primary:['Chest'],secondary:['Anterior Deltoid','Triceps','Core']} },
  { day:'Day 1', section:'Cables', name:'Cable Chest Fly', equipment:'Cable Machine', weight_range:'Light → 20 lbs', sets_target:3, reps_target:'12', instructions:['Set both pulleys at chest height','Step forward, arms slightly bent','Pull handles together in front of chest','Pause, then slowly return'], image_key:'cable-chest-fly', superset_group:null, sort_order:14, muscles:{primary:['Chest'],secondary:['Anterior Deltoid']} },

  // Machines
  { day:'Day 1', section:'Machines', name:'Overhead Press Machine', equipment:'Machine', weight_range:'15 → 40 lbs', sets_target:3, reps_target:'10', instructions:['Adjust seat to align handles with shoulders','Grip handles, press overhead','Pause at top, return slowly'], image_key:'overhead-press-machine', superset_group:null, sort_order:15, muscles:{primary:['Anterior Deltoid','Medial Deltoid'],secondary:['Triceps','Upper Chest']} },
  { day:'Day 1', section:'Machines', name:'Pec Deck Fly', equipment:'Machine', weight_range:'10 → 30 lbs', sets_target:3, reps_target:'12', instructions:['Sit upright with arms on pads','Bring pads together','Squeeze chest, return with control'], image_key:'pec-deck-fly', superset_group:null, sort_order:16, muscles:{primary:['Chest'],secondary:['Anterior Deltoid']} },
  { day:'Day 1', section:'Machines', name:'Lateral Raise Machine', equipment:'Machine', weight_range:'10 → 25 lbs', sets_target:3, reps_target:'12', instructions:['Sit with arms under pads','Raise arms outward to shoulder height','Pause, return slowly','Adjust seat for alignment'], image_key:'lateral-raise-machine', superset_group:null, sort_order:17, muscles:{primary:['Medial Deltoid'],secondary:['Anterior Deltoid','Upper Traps']} },
  { day:'Day 1', section:'Machines', name:'Machine Chest Press', equipment:'Machine', weight_range:'20 → 50 lbs', sets_target:3, reps_target:'10', instructions:['Adjust seat so handles align with mid-chest','Grip handles firmly','Press forward until arms are straight','Pause, then return under control'], image_key:'machine-chest-press', superset_group:null, sort_order:18, muscles:{primary:['Chest'],secondary:['Anterior Deltoid','Triceps']} },
  { day:'Day 1', section:'Machines', name:'Incline Chest Press Machine', equipment:'Machine', weight_range:'15 → 40 lbs', sets_target:3, reps_target:'12', instructions:['Sit in incline position','Grip handles, press forward/upward','Control descent, maintain posture'], image_key:'incline-chest-press-machine', superset_group:null, sort_order:19, muscles:{primary:['Upper Chest'],secondary:['Anterior Deltoid','Triceps']} },

  // Superset @ mat
  { day:'Day 1', section:'Superset @ mat', name:'Overhead Tricep Extension (2-arm)', equipment:'Dumbbell', weight_range:'10 → 20 lbs', sets_target:3, reps_target:'12', instructions:['Hold one dumbbell with both hands overhead','Lower behind head, elbows tucked','Extend arms, avoid flaring'], image_key:'overhead-tricep-extension-2arm', superset_group:'superset-mat-d1', sort_order:20, muscles:{primary:['Triceps'],secondary:['Core']} },
  { day:'Day 1', section:'Superset @ mat', name:'Overhead Tricep Extension (1-arm)', equipment:'Dumbbell', weight_range:'5 → 10 lbs', sets_target:3, reps_target:'12 per arm', instructions:['Hold dumbbell overhead in one hand','Lower behind head, elbow near ear','Extend arm straight up','Avoid flaring elbow'], image_key:'overhead-tricep-extension-1arm', superset_group:'superset-mat-d1', sort_order:21, muscles:{primary:['Triceps'],secondary:['Core']} },
  { day:'Day 1', section:'Superset @ mat', name:'Z-Press', equipment:'Dumbbells', weight_range:'5 → 12 lbs', sets_target:3, reps_target:'10', instructions:['Sit on floor, legs straight out','Hold dumbbells at shoulders','Press directly overhead without leaning','Keep core engaged, lower slowly'], image_key:'z-press', superset_group:'superset-mat-d1', sort_order:22, muscles:{primary:['Anterior Deltoid','Medial Deltoid'],secondary:['Triceps','Core','Upper Chest']} },

  // ==================== DAY 2 — PULL ====================

  // Warmup + core
  { day:'Day 2', section:'Warmup + core', name:'EZ Bar Curl', equipment:'EZ Bar', weight_range:'15 → 30 lbs', sets_target:3, reps_target:'10', instructions:['Stand upright, grip bar with underhand grip','Curl to shoulders, elbows stationary','Lower slowly'], image_key:'ez-bar-curl', superset_group:null, sort_order:1, muscles:{primary:['Biceps'],secondary:['Brachialis','Forearms']} },

  // Superset A
  { day:'Day 2', section:'Superset A', name:'Bent-Over Dumbbell Row', equipment:'Dumbbells', weight_range:'10 → 20 lbs', sets_target:3, reps_target:'10', instructions:['Hinge at hips, back flat, core braced','Hold dumbbells with palms facing in','Pull to sides of ribcage, squeezing shoulder blades','Lower slowly with control'], image_key:'bent-over-dumbbell-row', superset_group:'superset-a-d2', sort_order:2, muscles:{primary:['Lats','Rhomboids'],secondary:['Biceps','Posterior Deltoid','Traps']} },
  { day:'Day 2', section:'Superset A', name:'Alternating Dumbbell Curl', equipment:'Dumbbells', weight_range:'8 → 15 lbs', sets_target:3, reps_target:'10 per arm', instructions:['Stand tall with dumbbells at sides','Curl one arm up, palm facing shoulder','Keep elbow tucked and avoid swinging','Lower, then alternate'], image_key:'alternating-dumbbell-curl', superset_group:'superset-a-d2', sort_order:3, muscles:{primary:['Biceps'],secondary:['Brachialis','Forearms']} },
  { day:'Day 2', section:'Superset A', name:'Dumbbell Shrugs', equipment:'Dumbbells', weight_range:'15 → 25 lbs', sets_target:3, reps_target:'15', instructions:['Stand upright with arms at sides','Shrug shoulders up as high as possible','Hold briefly, lower with control'], image_key:'dumbbell-shrugs', superset_group:'superset-a-d2', sort_order:4, muscles:{primary:['Upper Traps'],secondary:['Rhomboids','Levator Scapulae']} },

  // Superset B
  { day:'Day 2', section:'Superset B', name:'Hammer Curl', equipment:'Dumbbells', weight_range:'10 → 15 lbs', sets_target:3, reps_target:'10', instructions:['Palms facing in, curl dumbbells up','Keep elbows close to body','Lower with control'], image_key:'hammer-curl', superset_group:'superset-b-d2', sort_order:5, muscles:{primary:['Brachialis','Brachioradialis'],secondary:['Biceps']} },
  { day:'Day 2', section:'Superset B', name:'Rear Delt Fly', equipment:'Dumbbells', weight_range:'5 → 10 lbs', sets_target:3, reps_target:'15', instructions:['Bend at hips, arms slightly bent','Raise arms out to sides, pause','Return slowly'], image_key:'rear-delt-fly', superset_group:'superset-b-d2', sort_order:6, muscles:{primary:['Posterior Deltoid'],secondary:['Rhomboids','Middle Traps']} },

  // Superset C
  { day:'Day 2', section:'Superset C', name:'Incline Dumbbell Back Fly', equipment:'Incline Bench, Dumbbells', weight_range:'5 → 10 lbs', sets_target:3, reps_target:'15', instructions:['Lie face down on incline bench','Arms hanging, slight bend in elbows','Raise out to sides, squeeze upper back','Control descent'], image_key:'incline-dumbbell-back-fly', superset_group:'superset-c-d2', sort_order:7, muscles:{primary:['Posterior Deltoid','Rhomboids'],secondary:['Middle Traps']} },
  { day:'Day 2', section:'Superset C', name:'Trap 3 Raise', equipment:'Incline Bench, Dumbbells', weight_range:'3 → 8 lbs', sets_target:3, reps_target:'15', instructions:['Lie face down, thumbs up','Raise arms in "Y" shape overhead','Squeeze traps, lower slowly'], image_key:'trap-3-raise', superset_group:'superset-c-d2', sort_order:8, muscles:{primary:['Lower Traps','Serratus Anterior'],secondary:['Posterior Deltoid']} },
  { day:'Day 2', section:'Superset C', name:'Incline Dumbbell Curl', equipment:'Incline Bench, Dumbbells', weight_range:'8 → 12 lbs', sets_target:3, reps_target:'10', instructions:['Sit back on incline bench','Let arms hang straight down','Curl dumbbells up without moving upper arms','Lower to full extension'], image_key:'incline-dumbbell-curl', superset_group:'superset-c-d2', sort_order:9, muscles:{primary:['Biceps'],secondary:['Brachialis']} },

  // Standing Cables
  { day:'Day 2', section:'Standing Cables', name:'Cable Face Pull', equipment:'Rope Attachment', weight_range:'15 → 30 lbs', sets_target:3, reps_target:'12', instructions:['Set rope at face height','Pull rope toward eyes with elbows high','Focus on upper back contraction'], image_key:'cable-face-pull', superset_group:null, sort_order:10, muscles:{primary:['Posterior Deltoid','Upper Traps'],secondary:['Rhomboids','External Rotators']} },
  { day:'Day 2', section:'Standing Cables', name:'Straight-Arm Pulldown', equipment:'Cable Machine', weight_range:'15 → 30 lbs', sets_target:3, reps_target:'12', instructions:['Stand tall with arms extended straight','Pull bar to thighs using lats','Keep arms straight throughout'], image_key:'straight-arm-pulldown', superset_group:null, sort_order:11, muscles:{primary:['Lats'],secondary:['Teres Major','Triceps']} },
  { day:'Day 2', section:'Standing Cables', name:'Close-Grip Cable Row', equipment:'Cable Machine', weight_range:'25 → 50 lbs', sets_target:3, reps_target:'12', instructions:['Use narrow V-bar handle','Pull to upper abs, keep chest up','Pause, then return with control'], image_key:'close-grip-cable-row', superset_group:null, sort_order:12, muscles:{primary:['Lats','Rhomboids','Middle Traps'],secondary:['Biceps','Posterior Deltoid']} },

  // Seated Cables
  { day:'Day 2', section:'Seated Cables', name:'Seated Cable Row', equipment:'Cable Machine', weight_range:'25 → 50 lbs', sets_target:3, reps_target:'12', instructions:['Sit upright with knees slightly bent','Pull handle to torso, elbows in','Squeeze shoulder blades together','Slowly extend arms'], image_key:'seated-cable-row', superset_group:null, sort_order:13, muscles:{primary:['Lats','Rhomboids','Middle Traps'],secondary:['Biceps','Posterior Deltoid']} },
  { day:'Day 2', section:'Seated Cables', name:'Wide-Grip Lat Pulldown', equipment:'Cable Machine', weight_range:'25 → 50 lbs', sets_target:3, reps_target:'10', instructions:['Grip bar wider than shoulder-width','Pull bar to upper chest','Pause and return slowly'], image_key:'wide-grip-lat-pulldown', superset_group:null, sort_order:14, muscles:{primary:['Lats'],secondary:['Biceps','Posterior Deltoid']} },

  // Machines
  { day:'Day 2', section:'Machines', name:'Lat Pull Machine', equipment:'Machine', weight_range:'25 → 50 lbs', sets_target:3, reps_target:'10', instructions:['Adjust thigh pad and grip wide bar','Pull bar to chest, squeeze lats','Control return to start'], image_key:'lat-pull-machine', superset_group:null, sort_order:15, muscles:{primary:['Lats'],secondary:['Biceps','Posterior Deltoid']} },
  { day:'Day 2', section:'Machines', name:'Assisted Pull-Up', equipment:'Assisted Machine', weight_range:'Bodyweight Assist', sets_target:3, reps_target:'5-8', instructions:['Select appropriate assistance level','Grip bar wider than shoulders','Pull chest to bar, control descent'], image_key:'assisted-pull-up', superset_group:null, sort_order:16, muscles:{primary:['Lats','Biceps'],secondary:['Rhomboids','Core']} },

  // Superset @ mat
  { day:'Day 2', section:'Superset @ mat', name:'Band Pull-Apart', equipment:'Resistance Band', weight_range:'Light Band', sets_target:3, reps_target:'15', instructions:['Hold band at chest height','Pull ends apart, squeeze shoulder blades','Return with control'], image_key:'band-pull-apart', superset_group:'superset-mat-d2', sort_order:17, muscles:{primary:['Posterior Deltoid','Rhomboids'],secondary:['Middle Traps']} },
  { day:'Day 2', section:'Superset @ mat', name:'Superman Hold', equipment:'Bodyweight', weight_range:'N/A', sets_target:3, reps_target:'30s', instructions:['Lie face down, arms extended','Lift arms, chest, and legs off floor','Hold position, engage glutes/core'], image_key:'superman-hold', superset_group:'superset-mat-d2', sort_order:18, muscles:{primary:['Erector Spinae','Glutes'],secondary:['Hamstrings','Posterior Deltoid']} },

  // ==================== DAY 3 — LEGS ====================

  // Warmup + core
  { day:'Day 3', section:'Warmup + core', name:'Barbell Back Squat', equipment:'Barbell', weight_range:'30 → 60 lbs', sets_target:3, reps_target:'8-10', instructions:['Barbell on upper traps','Squat to parallel, maintain upright chest','Drive through heels'], image_key:'barbell-back-squat', superset_group:null, sort_order:1, muscles:{primary:['Quads','Glutes'],secondary:['Hamstrings','Adductors','Core']} },

  // Superset A
  { day:'Day 3', section:'Superset A', name:'Goblet Squat', equipment:'Dumbbell', weight_range:'15 → 30 lbs', sets_target:3, reps_target:'12', instructions:['Stand with feet shoulder-width apart','Hold dumbbell at chest, elbows tucked','Squat down until thighs are parallel','Push through heels to stand up'], image_key:'goblet-squat', superset_group:'superset-a-d3', sort_order:2, muscles:{primary:['Quads','Glutes'],secondary:['Core','Adductors']} },
  { day:'Day 3', section:'Superset A', name:'Straight-Leg Back Lunge', equipment:'Dumbbells', weight_range:'10 → 20 lbs', sets_target:3, reps_target:'10 per leg', instructions:['Step back with minimal knee bend','Hinge forward slightly at hips','Push through heel to return'], image_key:'straight-leg-back-lunge', superset_group:'superset-a-d3', sort_order:3, muscles:{primary:['Glutes','Hamstrings'],secondary:['Quads','Adductors']} },
  { day:'Day 3', section:'Superset A', name:'Standing Calf Raises', equipment:'Dumbbells (optional)', weight_range:'Bodyweight → 20 lbs', sets_target:3, reps_target:'20', instructions:['Stand upright, feet hip-width apart','Raise heels as high as possible','Pause, then lower slowly'], image_key:'standing-calf-raises', superset_group:'superset-a-d3', sort_order:4, muscles:{primary:['Gastrocnemius','Soleus'],secondary:['Tibialis Anterior']} },

  // Superset B
  { day:'Day 3', section:'Superset B', name:'Romanian Deadlift', equipment:'Dumbbells', weight_range:'15 → 30 lbs', sets_target:3, reps_target:'12', instructions:['Stand tall with dumbbells in front','Hinge at hips, slight knee bend','Lower weights along shins','Squeeze glutes to return up'], image_key:'romanian-deadlift', superset_group:'superset-b-d3', sort_order:5, muscles:{primary:['Hamstrings','Glutes'],secondary:['Lower Back','Adductors']} },
  { day:'Day 3', section:'Superset B', name:'Plie Squat', equipment:'Dumbbell', weight_range:'10 → 20 lbs', sets_target:3, reps_target:'12', instructions:['Stand with feet wide, toes pointed out','Hold dumbbell at chest','Lower down in a squat, keep torso upright'], image_key:'plie-squat', superset_group:'superset-b-d3', sort_order:6, muscles:{primary:['Adductors','Glutes'],secondary:['Quads']} },
  { day:'Day 3', section:'Superset B', name:'Single-Leg Deadlift', equipment:'Dumbbells', weight_range:'10 → 15 lbs', sets_target:3, reps_target:'10 per leg', instructions:['Stand on one leg, other leg extends back','Lower dumbbells as torso hinges forward','Return to standing with balance'], image_key:'single-leg-deadlift', superset_group:'superset-b-d3', sort_order:7, muscles:{primary:['Hamstrings','Glutes'],secondary:['Core','Lower Back']} },

  // Superset C
  { day:'Day 3', section:'Superset C', name:'Side Lunges', equipment:'Dumbbells', weight_range:'10 → 20 lbs', sets_target:3, reps_target:'10 per leg', instructions:['Step to the side, bend lead knee','Keep trailing leg straight','Push back to center'], image_key:'side-lunges', superset_group:'superset-c-d3', sort_order:8, muscles:{primary:['Adductors','Glutes','Quads'],secondary:['Hamstrings']} },
  { day:'Day 3', section:'Superset C', name:'Reverse Lunges', equipment:'Dumbbells', weight_range:'10 → 20 lbs', sets_target:3, reps_target:'10 per leg', instructions:['Step one foot back, lower until both knees at 90°','Keep chest upright','Push through front foot to return'], image_key:'reverse-lunges', superset_group:'superset-c-d3', sort_order:9, muscles:{primary:['Quads','Glutes'],secondary:['Hamstrings','Core']} },
  { day:'Day 3', section:'Superset C', name:'Split Squat (Both Feet Grounded)', equipment:'Dumbbells', weight_range:'10 → 20 lbs', sets_target:3, reps_target:'10 per leg + 10s hold', instructions:['Take a long stance, both feet planted','Lower until front thigh is parallel','Hold final rep for 10 seconds'], image_key:'split-squat', superset_group:'superset-c-d3', sort_order:10, muscles:{primary:['Quads','Glutes'],secondary:['Hamstrings','Adductors']} },

  // Superset D
  { day:'Day 3', section:'Superset D', name:'Dumbbell Step-Up', equipment:'Dumbbells, Bench/Box', weight_range:'10 → 20 lbs', sets_target:3, reps_target:'10 per leg', instructions:['Step one foot onto bench','Drive through heel to lift body','Bring opposite knee up, then step down'], image_key:'dumbbell-step-up', superset_group:'superset-d-d3', sort_order:11, muscles:{primary:['Quads','Glutes'],secondary:['Hamstrings','Calves']} },
  { day:'Day 3', section:'Superset D', name:'Bulgarian Split Squat', equipment:'Dumbbells, Bench', weight_range:'10 → 20 lbs', sets_target:3, reps_target:'10 per leg', instructions:['Rear foot elevated on bench','Lower until front thigh is parallel','Push through front heel to rise'], image_key:'bulgarian-split-squat', superset_group:'superset-d-d3', sort_order:12, muscles:{primary:['Quads','Glutes'],secondary:['Hamstrings','Adductors']} },

  // Superset E
  { day:'Day 3', section:'Superset E', name:'Kettlebell Sumo Squat to Press', equipment:'Kettlebell', weight_range:'10 → 25 lbs', sets_target:3, reps_target:'12', instructions:['Wide stance, hold kettlebell low','Squat down, press overhead as you rise','Control both movements'], image_key:'kettlebell-sumo-squat-to-press', superset_group:'superset-e-d3', sort_order:13, muscles:{primary:['Glutes','Adductors','Quads'],secondary:['Anterior Deltoid','Core']} },
  { day:'Day 3', section:'Superset E', name:'Jump Squats', equipment:'Bodyweight', weight_range:'N/A', sets_target:3, reps_target:'20', instructions:['Perform deep squat, explode upward','Land softly, immediately repeat','Use arms for momentum'], image_key:'jump-squats', superset_group:'superset-e-d3', sort_order:14, muscles:{primary:['Quads','Glutes'],secondary:['Hamstrings','Calves','Core']} },

  // Machines
  { day:'Day 3', section:'Machines', name:'Cable Glute Kickback', equipment:'Cable Machine', weight_range:'10 → 20 lbs', sets_target:3, reps_target:'10 per leg', instructions:['Strap ankle to low pulley','Kick leg straight back, squeeze glute','Return slowly'], image_key:'cable-glute-kickback', superset_group:null, sort_order:15, muscles:{primary:['Glutes'],secondary:['Hamstrings']} },
  { day:'Day 3', section:'Machines', name:'Leg Press', equipment:'Machine', weight_range:'50 → 100 lbs', sets_target:3, reps_target:'10', instructions:['Sit with feet hip-width on platform','Lower platform to 90° at knees','Press through heels to extend legs'], image_key:'leg-press', superset_group:null, sort_order:16, muscles:{primary:['Quads','Glutes'],secondary:['Hamstrings','Adductors']} },
  { day:'Day 3', section:'Machines', name:'Hip Abduction', equipment:'Machine', weight_range:'30 → 60 lbs', sets_target:3, reps_target:'12', instructions:['Sit with outer thighs against pads','Push legs outward','Pause, return slowly'], image_key:'hip-abduction', superset_group:null, sort_order:17, muscles:{primary:['Glutes Medius','TFL'],secondary:['Hip External Rotators']} },
  { day:'Day 3', section:'Machines', name:'Hip Adduction', equipment:'Machine', weight_range:'30 → 60 lbs', sets_target:3, reps_target:'12', instructions:['Sit with inner thighs against pads','Squeeze legs together','Pause, return slowly'], image_key:'hip-adduction', superset_group:null, sort_order:18, muscles:{primary:['Adductors'],secondary:['Glutes','Inner Quads']} },

  // Bands
  { day:'Day 3', section:'Bands', name:'Lateral Band Walk', equipment:'Resistance Band', weight_range:'Light Band', sets_target:3, reps_target:'10 per direction', instructions:['Band around thighs or ankles','Step side-to-side, maintain squat stance','Keep constant tension on band'], image_key:'lateral-band-walk', superset_group:null, sort_order:19, muscles:{primary:['Glutes Medius','TFL'],secondary:['Hip Abductors']} },
  { day:'Day 3', section:'Bands', name:'Groucho Walk', equipment:'Band (optional)', weight_range:'Bodyweight → Light Band', sets_target:3, reps_target:'30s', instructions:['Walk in deep squat position','Stay low, keep knees aligned','Step wide, slow and controlled'], image_key:'groucho-walk', superset_group:null, sort_order:20, muscles:{primary:['Quads','Glutes Medius'],secondary:['Adductors','Core']} },

  // Superset @ mat
  { day:'Day 3', section:'Superset @ mat', name:'Dumbbell Glute Bridge', equipment:'Dumbbell', weight_range:'10 → 25 lbs', sets_target:3, reps_target:'15', instructions:['Lie on back, knees bent','Rest dumbbell on hips','Drive through heels, lift hips','Squeeze glutes at top'], image_key:'dumbbell-glute-bridge', superset_group:'superset-mat-d3', sort_order:21, muscles:{primary:['Glutes'],secondary:['Hamstrings','Core']} },
  { day:'Day 3', section:'Superset @ mat', name:'Wall Sit (with Ball Squeeze)', equipment:'Ball', weight_range:'Bodyweight', sets_target:3, reps_target:'45s', instructions:['Back against wall, knees at 90°','Squeeze ball between thighs','Keep shoulders and back flat'], image_key:'wall-sit', superset_group:'superset-mat-d3', sort_order:22, muscles:{primary:['Quads'],secondary:['Glutes','Hamstrings','Adductors']} },
];
